package br.com.leitovivo.domain;

public enum EventoLeito {
    RESERVAR_LEITO,
    CANCELAR_RESERVA,
    INTERNAR_PACIENTE,
    REGISTRAR_ALTA,
    FINALIZAR_HIGIENIZACAO,
    ENVIAR_MANUTENCAO,
    FINALIZAR_MANUTENCAO
}
